import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent

plugins {
    id "java-library"
    id "de.monticore.generator"
    id "jacoco"
}




dependencies {
    // Depend on the MontiCore language library (which in term depends on the runtime)
    grammar "de.monticore:monticore-grammar:$mc_version"

    implementation "org.apache.commons:commons-lang3:3.9"
    implementation "commons-cli:commons-cli:1.4"

    testImplementation "org.junit.jupiter:junit-jupiter:$junit_version"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation testFixtures("de.monticore:monticore-grammar:$mc_version")
}

generateMCGrammars {
    // The mc4 grammars are build from the src/main/grammars directory by default
    // You do not have to configure anything, the de.monticore.generator plugin does it all
    // Reasonable defaults are used, further details: https://monticore.github.io/monticore/docs/Gradle/
}

